# Generated by Django 3.2.7 on 2023-05-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producto',
        ),
    ]
