# Generated by Django 3.2.7 on 2023-05-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-created'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
