# Generated by Django 3.2.7 on 2023-05-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image1',
            field=models.ImageField(upload_to='productos', verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image2',
            field=models.ImageField(upload_to='productos', verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image3',
            field=models.ImageField(upload_to='productos', verbose_name='Imagen3'),
        ),
    ]
