# Generated by Django 3.2.7 on 2023-05-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20230515_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producto',
        ),
    ]
