# Generated by Django 3.2.7 on 2023-05-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_categoriasprod_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasprod',
            options={'ordering': ['-created'], 'verbose_name': 'categoiriaProd', 'verbose_name_plural': 'categoriasProd'},
        ),
    ]
