# Generated by Django 3.2.7 on 2023-05-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_categoriasprod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasprod',
            options={'ordering': ['created'], 'verbose_name': 'categoiriaProd', 'verbose_name_plural': 'categoriasProd'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['created'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.CreateModel(
            name='productos_perros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('image1', models.ImageField(upload_to='productos', verbose_name='Imagen1')),
                ('image2', models.ImageField(upload_to='productos', verbose_name='Imagen2')),
                ('precio', models.FloatField(null=True, verbose_name='precio')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direccion Web')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoriasprod')),
            ],
            options={
                'verbose_name': 'producto_perro',
                'verbose_name_plural': 'productos_perros',
                'ordering': ['created'],
            },
        ),
    ]
