# Generated by Django 3.2.7 on 2023-05-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20230517_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos_perros',
            name='image2',
        ),
    ]
