# Generated by Django 3.2.7 on 2023-05-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_productos_perros_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image2',
        ),
    ]
