# Generated by Django 3.2.7 on 2023-05-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_productos_papitas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos_papitas',
            new_name='porciones',
        ),
    ]
