# Generated by Django 3.2.7 on 2023-05-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_rename_productos_papitas_porciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porciones',
            options={'ordering': ['created'], 'verbose_name': 'porcion', 'verbose_name_plural': 'porciones'},
        ),
    ]
