# Generated by Django 3.2.7 on 2023-05-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_alter_porciones_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='hamburguesas',
        ),
        migrations.AlterModelOptions(
            name='hamburguesas',
            options={'ordering': ['created'], 'verbose_name': 'hamburguesa', 'verbose_name_plural': 'hamburguesas'},
        ),
    ]
