# Generated by Django 3.2.7 on 2023-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_auto_20230526_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesas',
            name='observaciones',
            field=models.TextField(default=1, max_length=100, verbose_name='Observaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamburguesas',
            name='precio_ver',
            field=models.FloatField(null=True, verbose_name='precio'),
        ),
    ]
