# Generated by Django 3.2.7 on 2023-06-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_auto_20230531_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesas',
            name='precio_ver',
            field=models.FloatField(null=True, verbose_name='precio_ver'),
        ),
    ]
