# Generated by Django 3.2.7 on 2023-06-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_alter_hamburguesas_precio_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesas',
            name='observaciones',
        ),
    ]
