# Generated by Django 3.2.7 on 2023-06-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_remove_hamburguesas_precio_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos_alitas',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='productos_costillas',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='productos_perros',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='productos_picadas',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='productos_salchipapa',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='porciones',
        ),
        migrations.DeleteModel(
            name='productos_alitas',
        ),
        migrations.DeleteModel(
            name='productos_costillas',
        ),
        migrations.DeleteModel(
            name='productos_perros',
        ),
        migrations.DeleteModel(
            name='productos_picadas',
        ),
        migrations.DeleteModel(
            name='productos_salchipapa',
        ),
    ]
