# Generated by Django 3.2.7 on 2023-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_auto_20230602_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesas',
            name='descrip',
            field=models.TextField(default=1, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
