# Generated by Django 3.2.7 on 2023-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0028_hamburguesas_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaobservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='hamburguesas',
            name='observaciones',
        ),
    ]
