# Generated by Django 3.2.7 on 2023-06-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_auto_20230610_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajaobservaciones',
            options={'verbose_name': 'observacion', 'verbose_name_plural': 'observaciones'},
        ),
    ]
