# Generated by Django 3.2.7 on 2023-06-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0030_alter_cajaobservaciones_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cajaobservaciones',
        ),
    ]
